name: illinois
base: core20
version: "0.1"
summary: Bicep documentation generator
description: |
  Bicep documentation generator

grade: stable
confinement: strict

parts:
  illinois:
    plugin: nil
