name: illinois
base: core18
version: "0.1"
summary: Bicep documentation generator
description: |
  Bicep documentation generator

grade: stable
confinement: classic

parts:
  illinois:
    plugin: nil
