# After registering a name on build.snapcraft.io, commit an uncommented line:
# name: illinois
version: '0.1'
summary: Bicep documentation generator
description: |
  Bicep documentation generator

grade: stable
confinement: devmode

parts:
  my-part:
    plugin: nil
