name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet publish ./illinois.csproj --configuration Release --os linux --output ../bin

    - name: Prepare debian package
      run: |
        sed -i "s/\$\$AUTHOR\$\$/$GITHUB_ACTOR/g" ./debian/DEBIAN/control
        sed -i "s/\$\$EMAIL\$\$/$GITHUB_ACTOR\@users.noreply.github.com/g" ./debian/DEBIAN/control

    - name: Create debian package
      run: dpkg-deb --build ./debian ./bin/illinois.deb

