name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet publish ./illinois.csproj --configuration Release --os linux --output ../bin

    - name: Prepare debian package
      run: |
        sed -i "s/{COMMIT}/${GITHUB_RUN_ID}/g" ./DEBIAN/control
        sed -i "s/{AUTHOR}/${GITHUB_ACTOR}/g" ./DEBIAN/control
        sed -i "s/{EMAIL}/${GITHUB_ACTOR}@users.noreply.github.com/g" ./DEBIAN/control

    - name: Create debian package
      run: dpkg-deb --build ./ ./bin/illinois.deb

    - name: Upload debian package
      uses: actions/upload-artifact@v2
      with:
        name: illinois
        path: ./bin/illinois.deb

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Create Release
      id: create_release
      run: |
        response=$(curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d "{\"tag_name\":\"${{ github.ref }}\",\"name\":\"Release ${{ github.ref }}\",\"body\":\"Changes in this release:\n- Describe your changes here\",\"draft\":false,\"prerelease\":false}")

        echo "$response"

        upload_url=$(echo "$response" | jq -r '.upload_url' | sed 's/{?name,label}//')

        echo "$upload_url"

        curl \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/x-deb" \
          --data-binary @bin/illinois.deb \
          "$upload_url?name=$(basename bin/illinois.deb)"
