name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      working-directory: ./src
      run: |
        apt update
        apt install devscripts build-essential -y

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet publish ./illinois.csproj --configuration release --self-contained --runtime linux-x64 --output ../bin

    - name: Create debian package
      run: debuild -us -uc

    - name: Upload debian package
      uses: actions/upload-artifact@v2
      with:
        name: illinois
        path: ./bin/illinois.deb
