name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet publish ./illinois.csproj --configuration release --self-contained --runtime linux-x64 --output ../bin

    - name: Pack and Publish
      working-directory: ./src
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      run: |
        dotnet pack ./illinois.sln --configuration release
        dotnet nuget push "./illinois/bin/release/illinois.*.nupkg" --source "https://api.nuget.org/v3/index.json" --skip-duplicate --api-key "${NUGET_AUTH_TOKEN}"
